postgres:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "mysecretpassword"
  db: "postgres"
oss:
  endpoint: ""
  accessKey: ""
  secretKey: ""
ssl:
  enabled: true
  sslPort: 8443
  keyStore: "./keystore.jks"
  keyStoreAlias: "development"
  keyStorePassword: "development"
  privateKeyPassword: "development"